# This file determines some invitation style options

# Screenshots section describe all screenshots shiped with style
# Params names should be equals to file names without extension. Pictures
# extension should be '.png'
# Params values should be equals to screenshot desription
screenshots:
    invitation: "Appearance of the invitation"
    location: "Location of the invitation on a page"
